trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Run tests
- task: Maven@3
  displayName: 'Run Selenium Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
    options: '-pl tests -am'

# Publish Allure report 
- task: PublishAllureReport@1
  displayName: 'Publish Allure Report'
  condition: always()
  inputs:
    allureVersion: '2.27.0'
    testResultsDir: 'tests/target/allure-results'

# Publish Extent Spark HTML & PDF reports
- task: PublishPipelineArtifact@1
  displayName: 'Publish Extent Reports'
  condition: always()
  inputs:
    targetPath: 'tests/target/ExtentReports'
    artifact: 'ExtentReports'
    publishLocation: 'pipeline'
